import DefaultLayout from './DefaultLayout';
import dynamic from 'next/dynamic';
const NavBar = dynamic(() => import('../components/layoutComps/NavBar/NavBar'));
const Footer = dynamic(() => import('@/components/layoutComps/Footer/Footer'));
const Banner = dynamic(() => import('@/components/UiComps/Banner'));
import { jost } from '@/utils/fonts';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={`${jost.className} `}>
                <NavBar />

                <DefaultLayout>{children}</DefaultLayout>

                {/* <Banner/> */}

                <Footer />
            </body>
        </html>
    );
}
