import DefaultLayout from './DefaultLayout';
const NavBar = dynamic(() => import('../components/layoutComps/NavBar/NavBar'));
const Footer = dynamic(() => import('@/components/layoutComps/Footer/Footer'));
const Banner = dynamic(() => import('@/components/UiComps/Banner'));
import Loader from '@/components/UiComps/Loader';
import { Suspense } from 'react';
import dynamic from 'next/dynamic';
import { jost } from '@/utils/fonts';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={`${jost.className} `}>
                <NavBar />
                <Suspense fallback={<Loader />}>
                    <DefaultLayout>{children}</DefaultLayout>
                </Suspense>
                {/* <Banner/> */}
                <Suspense fallback={<Loader />}>
                    <Footer />
                </Suspense>
            </body>
        </html>
    );
}
