import DefaultLayout from './DefaultLayout';
import NavBar from '../components/layoutComps/NavBar/NavBar';
import Footer from '@/components/layoutComps/Footer/Footer';
import Banner from "@/components/UiComps/Banner"
import './globals.css';
import { jost } from '@/utils/fonts';
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={`${jost.className} `}>
                <NavBar />
                <DefaultLayout>{children}</DefaultLayout>
                {/* <Banner/> */}
                <Footer />
            </body>
        </html>
    );
}
