import DefaultLayout from './DefaultLayout';
import NavBar from '../components/layoutComps/NavBar/NavBar';
import Footer from '@/components/layoutComps/Footer/Footer';
import Banner from '@/components/UiComps/Banner';
import './globals.css';
import { jost } from '@/utils/fonts';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    // metadataBase: new URL(''),
    referrer: 'no-referrer',
    manifest: '', //url del manifest.json
    keywords: [],
    // robots: {
    //     index: true,
    //     follow: true,
    //     googleBot: { index: true, follow: true },
    // },
    verification:{
      google:"google-site-verification=id"  
    },
    // openGraph: {
    //     title: 'Create Next App',
    //     description: 'Generated by create next app',
    //     url: '',
    //     siteName: 'Qué trago hacer?',
    //     locale: 'es',
    //     type: 'website',
        
    // },
    colorScheme: 'light',
    creator: 'Isaias Garcia | Full Stack Dev',
    publisher: 'Isaias Garcia',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={`${jost.className} `}>
                <NavBar />
                <DefaultLayout>{children}</DefaultLayout>
                {/* <Banner/> */}
                <Footer />
            </body>
        </html>
    );
}
