import DefaultLayout from './DefaultLayout';
import NavBar from '../components/layoutComps/NavBar/NavBar';
import Footer from '@/components/layoutComps/Footer/Footer';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['200', '300', '400','500', '700'],
    style: ['normal', 'italic'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={poppins.className}>
                <NavBar />
                <DefaultLayout>{children}</DefaultLayout>
                <Footer />
            </body>
        </html>
    );
}
